### ISSUE TITLE
Rake pipeline:compile

### ISSUE THREAD

**Issue by Ortuna** [Ortuna/padrino-pipeline#20]
Getting error on a fresh install with just a single javascript file.  Perhaps it's trying to manipulate css assets that are not there?

``` bash
rake aborted!
undefined method `digest' for nil:NilClass
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/compilers/sprockets.rb:67:in `block in compile_assets'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/compilers/sprockets.rb:66:in `each'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/compilers/sprockets.rb:66:in `compile_assets'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/compilers/sprockets.rb:49:in `compile_css'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/compilers/sprockets.rb:16:in `compile'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/configuration.rb:32:in `compile'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/tasks/pipeline_tasks.rb:9:in `block in send_to_pipeline'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/tasks/pipeline_tasks.rb:7:in `each'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/tasks/pipeline_tasks.rb:7:in `send_to_pipeline'
/Users/ortuna/.rvm/gems/ruby-2.1.0/gems/padrino-pipeline-0.4.0/lib/padrino-pipeline/tasks/pipeline_tasks.rb:28:in `block (2 levels) in <top (required)>'
Tasks: TOP => pipeline:compile => pipeline:compile_css
(See full trace by running task with --trace)
```

**Comment by leemour** [comment]
Hi! Got the same error. How can I do it manually while it's being fixed?

**Comment by leemour** [comment]
This is how I did it manually (using my own paths and Bootstrap-sass):

``` ruby
namespace :assets do
  desc 'compile javascript assets'
  task :compile_js => :environment do
    sprockets = Sprockets::Environment.new(PADRINO_ROOT) do |env|
      env.logger = Logger.new STDOUT
    end
    sprockets.append_path File.join PADRINO_ROOT, 'app', 'assets', 'js'
    sprockets.append_path File.join Bootstrap.gem_path, 'vendor', 'assets', 'javascripts'
    outpath = File.join PADRINO_ROOT, 'public', 'js', 'application.js'

    asset = sprockets['application.js']
    asset.write_to outpath
    puts "successfully compiled js assets"
  end
end
```
